# Simple workflow for deploying static content to GitHub Pages
name: Deploy Static Content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      # CORRECTED: All subsequent steps now run inside your project folder
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./MineDash # <-- ADD THIS

      - name: Build
        run: pnpm run build
        working-directory: ./MineDash # <-- AND THIS

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The path is relative to the working-directory
          path: './dist'
        working-directory: ./MineDash # <-- AND THIS
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4